<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class KddeEdbStoreBundleEntityPertinenceProxy extends \Kdde\EdbStoreBundle\Entity\Pertinence implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setInSitu($inSitu)
    {
        $this->__load();
        return parent::setInSitu($inSitu);
    }

    public function getInSitu()
    {
        $this->__load();
        return parent::getInSitu();
    }

    public function setLocus(\Kdde\EdbStoreBundle\Entity\LocusInventionis $locus)
    {
        $this->__load();
        return parent::setLocus($locus);
    }

    public function getLocus()
    {
        $this->__load();
        return parent::getLocus();
    }

    public function setPertinenceArea(\Kdde\EdbStoreBundle\Entity\PertinenceArea $pertinenceArea)
    {
        $this->__load();
        return parent::setPertinenceArea($pertinenceArea);
    }

    public function getPertinenceArea()
    {
        $this->__load();
        return parent::getPertinenceArea();
    }

    public function setContext(\Kdde\EdbStoreBundle\Entity\PertinenceContext $context)
    {
        $this->__load();
        return parent::setContext($context);
    }

    public function getContext()
    {
        $this->__load();
        return parent::getContext();
    }

    public function setPertinencePosition(\Kdde\EdbStoreBundle\Entity\PertinencePosition $pertinencePosition)
    {
        $this->__load();
        return parent::setPertinencePosition($pertinencePosition);
    }

    public function getPertinencePosition()
    {
        $this->__load();
        return parent::getPertinencePosition();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'locus', 'pertinenceArea', 'context', 'pertinencePosition', 'inSitu');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}