security:            
  encoders:
    Kdde\EdbStoreBundle\Entity\User:
      algorithm: sha512
      encode-as-base64: true
      iterations: 10
               
  providers:
    main:
      entity: {class: Kdde\EdbStoreBundle\Entity\User }
    
  firewalls:
    main:
      pattern: ^/
      form_login:
        login_path:  /login
        check_path:  /login/check
      logout: true
      security: true
      anonymous: true
  
  access_control:
    - {path: ^/admin, roles: ROLE_ADMIN}
    - {path: ^/compiler, roles: [ROLE_COMPILER, ROLE_ADMIN] }
    - {path: ^/search/medium, roles: [ROLE_ADMIN, ROLE_MEDIUM, ROLE_ADVANCED, ROLE_COMPILER] }
    - {path: ^/search/advanced, roles: [ROLE_ADMIN, ROLE_ADVANCED, ROLE_COMPILER] }