security:
  encoders:
    Kdde\EdbStoreBundle\Entity\User:
      algorithm: sha512
      encode-as-base64: true
      iterations: 10
               
  providers:
    main:
      entity: {class: Kdde\EdbStoreBundle\Entity\User }
    
  firewalls:
    main:
      pattern: ^/
      form_login:
        login_path:  /login
        check_path:  /login/check
      logout: true
      security: true
      anonymous: true
  
  access_control:
    - {path: ^/admin, role: ROLE_ADMIN}
    - {path: ^/compiler, role: ROLE_COMPILER }
    - {path: ^/compiler, role: ROLE_ADMIN }
 