<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class KddeEdbStoreBundleEntityConservationProxy extends \Kdde\EdbStoreBundle\Entity\Conservation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setConservationLocation(\Kdde\EdbStoreBundle\Entity\ConservationLocation $conservationLocation)
    {
        $this->__load();
        return parent::setConservationLocation($conservationLocation);
    }

    public function getConservationLocation()
    {
        $this->__load();
        return parent::getConservationLocation();
    }

    public function setConservationContext(\Kdde\EdbStoreBundle\Entity\ConservationContext $conservationContext)
    {
        $this->__load();
        return parent::setConservationContext($conservationContext);
    }

    public function getConservationContext()
    {
        $this->__load();
        return parent::getConservationContext();
    }

    public function setConservationPosition(\Kdde\EdbStoreBundle\Entity\ConservationPosition $conservationPosition)
    {
        $this->__load();
        return parent::setConservationPosition($conservationPosition);
    }

    public function getConservationPosition()
    {
        $this->__load();
        return parent::getConservationPosition();
    }

    public function addEpigraph(\Kdde\EdbStoreBundle\Entity\Epigraph $epigraphes)
    {
        $this->__load();
        return parent::addEpigraph($epigraphes);
    }

    public function getEpigraphes()
    {
        $this->__load();
        return parent::getEpigraphes();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'conservationLocation', 'conservationContext', 'conservationPosition', 'epigraphes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}